// This file was generated by wio-init.
package main

import (
	"os"

	wio "github.com/Maki-Daisuke/go-whole-in-one"
)

func init() {
	wio.Name = "wio"
	wio.Version = "0.0.5"
}

func main() {
	// Customize here as you like.
	wio.Register("help", wio.HelpCommand)
	wio.Register("-h", wio.HelpCommand)
	wio.Register("--help", wio.HelpCommand)
	wio.Register("version", wio.VersionCommand)
	wio.Register("-v", wio.VersionCommand)
	wio.Register("--version", wio.VersionCommand)
	wio.Exec(os.Args[1:])
}
