// This file was generated by wio-init.
//go:generate wio generate
package main

import (
	"os"

	wio "github.com/Maki-Daisuke/go-whole-in-one"
)

func init() {
	wio.Name = "wio"
	wio.Version = "0.0.2"
}

func main() {
	// Customize here as you like.
	wio.Exec(os.Args[1:])
}
