// DO NOT EDIT! This file was generated by wio-init.
package main

import(
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strings"
	wio "github.com/Maki-Daisuke/go-whole-in-one"
)

var(
	data = ""
	hash = "D41D8CD98F00B204E9800998ECF8427E"
)

func init() {
	u, err := user.Current()
	if err != nil {
		panic(err)
	}
	unpackPath := filepath.Join(os.TempDir(), fmt.Sprintf("wiocache-%s-%s-%s-%s", wio.Name, wio.Version, u.Uid, hash))
	err = os.Mkdir(unpackPath, 0700)
	if os.IsExist(err) {
		// Do nothing because the data is already unpacked
	} else if err != nil {
		panic(err)
	} else if data != "" {
		wio.Unpack(unpackPath, strings.NewReader(data))
	}
	wio.SetEnv(unpackPath)
}
