// This file was generated by garry-init.
//go:generate garry generate
package main

import(
	"os"
	"github.com/Maki-Daisuke/garry"
)

func init() {
	garry.Name = "garry"
	garry.Version = "0.0.1"
}

func main() {
	// Customize here as you like.
	garry.Exec(os.Args[1:])
}
