// DO NOT EDIT! This file was generated by garry-init.
package main

import(
	//"archive/tar"
	//"compress/gzip"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"github.com/Maki-Daisuke/garry"
)

var(
	data = ""
	hash = "D41D8CD98F00B204E9800998ECF8427E"
)

func init() {
	unpackPath := filepath.Join(os.TempDir(), fmt.Sprintf("garrycache-%s-%s-%s", garry.Name, garry.Version, hash))
	os.Setenv("GARRYPATH", unpackPath)
	os.Setenv("PATH", fmt.Sprintf("%s%c%s", unpackPath, os.PathListSeparator, os.Getenv("PATH")))
	err := os.Mkdir(unpackPath, 0755)
	if os.IsExist(err) {
		// Package is already unpacked
		return
	} else if err != nil {
		panic(err)
	}
	if data == "" {
		return
	}
	cmd := exec.Command("tar", "-C", unpackPath, "-zxf", "-")
	cmd.Stdin = strings.NewReader(data)
	cmd.Stdout = nil
	cmd.Stderr = os.Stderr
	err = cmd.Run()
	if err != nil {
		panic(err)
	}
}
